### PR TITLE
Add Amex info to source.reference description

### PR DESCRIPTION
**Pull request by eoin-shaughnessy-cko**
# Description of changes in PR

[//]: # 'Please add your description here'

## Checklist

- [ ] Added a changelog entry to the `changelog.md` file in either `abc_spec` or `nas_spec`
- [ ] Contacted the Tech Docs team about any corresponding guides that need to be updated for www.checkout.com/docs

**Contributing options**: Look at [our documentation](https://checkout.atlassian.net/wiki/spaces/PD/pages/2169506663/API+ref+publication+process) for options to contribute to the API reference.

### CODE REVIEW

**Comment by eoin-shaughnessy-cko** [comment]
To resolve:

- Does the 'reference' description on the BankPayoutRequest tab (under [Request a payment or payout](https://api-reference.checkout.com/#operation/requestAPaymentOrPayout)) need updating? Currently, it has no info about character limits.
- Does the 'reference' description under [Request a session](https://api-reference.checkout.com/#operation/createSession) also need updating?

**Review by gareth-forshaw-cko — APPROVED** [review]

**Comment by eoin-shaughnessy-cko** [comment]
@checkout/gateway-product-cko Can I get a review, please? :)

**Review by jason-dantzer-cko — APPROVED** [review]

**Comment by eoin-shaughnessy-cko** [comment]
Thanks for reviewing, @gareth-forshaw-cko and @jason-dantzer-cko!

**Comment by eoin-shaughnessy-cko** [comment]
@checkout/payment-interfaces-cko Can I get a review, please?

**Comment by eoin-shaughnessy-cko** [comment]
@checkout/payment-interfaces-cko If the content changes look ok, can we get an approval?

**Review by punit-shah-cko — APPROVED** [review]

**Pull request merged**
