### PR TITLE
Add one term for references to American Express

### PR DESCRIPTION
**Pull request by eoin-shaughnessy-cko**

### CODE REVIEW

**Review by natasha-moore-cko — APPROVED** [review]

**Comment by eoin-shaughnessy-cko** [comment]
@checkout/gateway-product-cko Can I get a review, please? :)

**Comment by eoin-shaughnessy-cko** [comment]
@checkout/gateway-product-cko Can we get a review, please?

**Comment by eoin-shaughnessy-cko** [comment]
@mathew-tuvesson-cko @Joshua-Bedeau-cko @Enrica-Mameli-cko If the changes here look ok, would someone from Gateway be able to approve, please?

**Comment by eoin-shaughnessy-cko** [comment]
@checkout/gateway-product-cko Can we get a review?

**Pull request merged**
