### PR TITLE
issuing: Update API Specification

### PR DESCRIPTION
**Pull request by cko-devops**

### CODE REVIEW

**Comment by ben-ahmady-cko** [comment]
@punit-shah-cko this PR is a bit impossible to work out 😅 

Is there any reason not to merge `main` into `kookaburra`?

**Comment by punit-shah-cko** [comment]
> @punit-shah-cko this PR is a bit impossible to work out 😅
> 
> Is there any reason not to merge `main` into `kookaburra`?

No idea, I'm not involved with this 😄 
That question might be better aimed at @sundaran-kumar-cko?

**Comment by sundaran-kumar-cko** [comment]
> > @punit-shah-cko this PR is a bit impossible to work out 😅
> > Is there any reason not to merge `main` into `kookaburra`?
> 
> No idea, I'm not involved with this 😄 That question might be better aimed at @sundaran-kumar-cko?

this is a private branch for Issuing since we are not live yet. We only share the link with private beta clients.

**Comment by ben-ahmady-cko** [comment]
@sundaran-kumar-cko that's fine, but in that case could you mark this with "[DONOTMERGE]" or similar please?

**Pull request closed without merging**
