### PR TITLE
Wechat API reference private beta

### PR DESCRIPTION
**Pull request by andreas-alapert-cko**
# Description of changes in PR

[//]: # 'Added WeChat Pay NAS structure'
# 'Added WeChat Pay NAS structure'

### CODE REVIEW

**Comment by ben-ahmady-cko** [comment]
@andreas-alapert-cko I assume since this is private beta that you want to leave this link as long-lived and not merge this PR?

**Comment by andreas-alapert-cko** [comment]
> @andreas-alapert-cko I assume since this is private beta that you want to leave this link as long-lived and not merge this PR?

Correct, should I convert this PR to draft?

**Comment by ben-ahmady-cko** [comment]
No worries, I've stuck all the relevant bits on

**Comment by ben-ahmady-cko** [comment]
@andreas-alapert-cko Sorry this was actually my mistake, you can merge this if/when it's ready unless you're deliberately sharing the preview link

**Comment by andreas-alapert-cko** [comment]
> @andreas-alapert-cko Sorry this was actually my mistake, you can merge this if/when it's ready unless you're deliberately sharing the preview link

Would need approval again

**Review by sebastian-garcia-cardona-cko — APPROVED** [review]

**Comment by andreas-alapert-cko** [comment]
1 workflow awaiting approval - First-time contributors need a maintainer to approve running workflows
@sebastian-garcia-cardona-cko - Could you help with this? Thanks

**Comment by andreas-alapert-cko** [comment]
@sebastian-garcia-cardona-cko I don't have permissions to merge. Could you please do it? Thanks!

**Pull request merged**
