### PR TITLE
Remove hard coded ids

### PR DESCRIPTION
**Pull request by ben-ahmady-cko**
Command used (using `tok_` and `<TOKEN_ID>` as an example):

```
for i in `grep -rlE 'tok_[a-zA-Z0-9]*' abc_spec nas_spec | grep -v 'code_samples'`; do gsed -i -E -e "/qpay|pattern|example/ ! s/tok_.[a-zA-Z0-9]*/<TOKEN_ID>/g" $i; done
```

Changes are as follows (I don't know if I've missed any):

`bat_` -> `<BATCH_ID>`

`sid_` -> `<SESSION_ID>`

`ntf_` -> `<EVENT_NOTIFICATION_ID>`

`evt_` -> `<EVENT_ID>`

`src_` -> `<SOURCE_ID>`

`tok_` -> `<TOKEN_ID>`

`cus_` -> `<CUSTOMER_ID>`

`act_` -> `<ACTION_ID>`

`ras_` -> `<ASSESSMENT_ID>`

`pay_` -> `<PAYMENT_ID>`

`pl_` -> `<PAYMENT_LINK_ID`>

**Not all of these will appear in this PR as some were only under `example` or `pattern` keys**

### CODE REVIEW

**Review by jack-hutchinson-cko — APPROVED** [review]
LGTM

**Review by jack-hutchinson-cko — APPROVED** [review]

**Comment by ben-ahmady-cko** [comment]
OK so I've thought about this more @chrisi-webster-cko @jack-hutchinson-cko and I think we're best off removing the examples in certain cases and just sticking with the patterns, that will make this much simpler to do as a one-off

@chrisi-webster-cko do you know who we could speak to about verifying some of the regex patterns in the API that are missing (currently just listed as examples)?

Screenshot 2021-09-22 at 11 16 04

**Comment by chrisi-webster-cko** [comment]
> OK so I've thought about this more @chrisi-webster-cko @jack-hutchinson-cko and I think we're best off removing the examples in certain cases and just sticking with the patterns, that will make this much simpler to do as a one-off
> 
> @chrisi-webster-cko do you know who we could speak to about verifying some of the regex patterns in the API that are missing (currently just listed as examples)?
> 
> Screenshot 2021-09-22 at 11 16 04

This is done by each team separately, so it would be a case of asking them all. I wonder whether it will be a problem though if we just take charge? We've never really had push back from engineers about changes to the API reference .

**Comment by ben-ahmady-cko** [comment]
> > OK so I've thought about this more @chrisi-webster-cko @jack-hutchinson-cko and I think we're best off removing the examples in certain cases and just sticking with the patterns, that will make this much simpler to do as a one-off
> > @chrisi-webster-cko do you know who we could speak to about verifying some of the regex patterns in the API that are missing (currently just listed as examples)?
> > Screenshot 2021-09-22 at 11 16 04
> 
> This is done by each team separately, so it would be a case of asking them all. I wonder whether it will be a problem though if we just take charge? We've never really had push back from engineers about changes to the API reference .

Probably not: let's discuss with Jack when he's back

**Pull request closed without merging**
