### PR TITLE
Update PHP code samples

### PR DESCRIPTION
**Pull request by rsaestrela**
This commit adds and replaces existing PHP code samples to match the SDK >2.0.0 usage.

# Description of changes in PR

[//]: # 'Please add your description here'

## Checklist

- [x] Added a changelog entry on the `swagger.yaml` file
- [ N/A] Contacted the Tech Docs team about any corresponding guides that need to be updated for www.checkout.com/docs

**Contributing options**: Look at [our documentation](https://checkout.atlassian.net/wiki/spaces/PD/pages/2169506663/API+ref+publication+process) for options to contribute to the API reference.

### CODE REVIEW

**Review by ioan-ghisoi-cko — DISMISSED** [review]

**Review by ben-ahmady-cko — DISMISSED** [review]
Johnny has already approved :)

**Review by ioan-ghisoi-cko — DISMISSED** [review]

**Comment by ioan-ghisoi-cko** [comment]
can you check the conflicts @rsaestrela

**Comment by rsaestrela** [comment]
> can you check the conflicts @rsaestrela

Done

**Review by ioan-ghisoi-cko — APPROVED** [review]

**Review by ioan-ghisoi-cko — DISMISSED** [review]

**Review by ben-ahmady-cko — DISMISSED** [review]

**Review by ioan-ghisoi-cko — APPROVED** [review]

**Comment by ioan-ghisoi-cko** [comment]
@ben-ahmady-cko When you have a second can you please review and merge?

**Review by ben-ahmady-cko — APPROVED** [review]

**Pull request merged**
